### ISSUE TITLE
Rename `azeventhubs` constructor methods to reflect that a `Result` is returned

### ISSUE THREAD

**Issue by minghuaw** [minghuaw/azure-sdk-for-rust#11]
The current constructor methods for `EventHubConnection`, `EventHubConsumerClient`, and `EventHubProducerClient` are in the form of `from_xxx` but returns a `Result`. This seems not strictly following the convention that `from_xxx` methods should not return a result, and it should be changed to be in the form of `try_from_xxx` if a result is returned.

**Comment by minghuaw** [comment]
Summary of method name change proposal(s): 

1. `from_connection_string()` -> `try_from_connection_string()`
2. `from_connection_string()` -> `new_from_connection_string()`

This comment will be updated as more ideas show up

**Comment by jackgerrits** [comment]
I don't have a strong opinion here. I like the removal of `namespace` from the name though as to me the key differentiating factor here is the method to authenticate.

**Comment by minghuaw** [comment]
> I don't have a strong opinion here. I like the removal of `namespace` from the name though as to me the key differentiating factor here is the method to authenticate.

I am planning to make this change in "0.14.1" and mark the original methods as deprecated

**Comment by minghuaw** [comment]
A new version "0.14.1" has been released on crates.io
